language: java
jdk:
  - openjdk8

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

addons:
  sonarcloud:
    organization: "antkorwin-github"
    token:
      secure: $SONAR_CLOUD_KEY

after_success:
  - mvn cobertura:cobertura
  - bash <(curl -s https://codecov.io/bash)